# Generated by Django 3.1.1 on 2021-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210204_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=200, null=True)),
                ('sub_heading', models.CharField(max_length=200, null=True)),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
