# Generated by Django 3.1.6 on 2021-02-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('introduction', models.CharField(max_length=600, null=True)),
                ('facebook_profile_link', models.CharField(max_length=300, null=True)),
                ('instagram_profile_link', models.CharField(max_length=300, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
